;; GENERATED, DO NOT MODIFY!!
(ns mayachen350.casinobot.gambling.gen-data.gi-data)

(def gi-chara-data [
  ["Amber" 4 :f :pyro :bow :mondstadt]
  ["Barbara" 4 :f :hydro :catalyst :mondstadt]
  ["Beidou" 4 :f :electro :claymore :liyue]
  ["Bennett" 4 :m :pyro :sword :mondstadt]
  ["Chongyun" 4 :m :cryo :claymore :liyue]
  ["Diluc" 5 :m :pyro :claymore :mondstadt]
  ["Fischl" 4 :f :electro :bow :mondstadt]
  ["Jean" 5 :f :anemo :sword :mondstadt]
  ["Kaeya" 4 :m :cryo :sword :mondstadt]
  ["Keqing" 5 :f :electro :sword :liyue]
  ["Lisa" 4 :f :electro :catalyst :mondstadt]
  ["Mona" 5 :f :hydro :catalyst :mondstadt]
  ["Ningguang" 4 :f :geo :catalyst :liyue]
  ["Noelle" 4 :f :geo :claymore :mondstadt]
  ["Qiqi" 5 :f :cryo :sword :liyue]
  ["Razor" 4 :m :electro :claymore :mondstadt]
  ["Sucrose" 4 :f :anemo :catalyst :mondstadt]
  ["Venti" 5 :m :anemo :bow :mondstadt]
  ["Xiangling" 4 :f :pyro :polearm :liyue]
  ["Xingqiu" 4 :m :hydro :sword :liyue]
  ["Klee" 5 :f :pyro :catalyst :mondstadt]
  ["Diona" 4 :f :cryo :bow :mondstadt]
  ["Tartaglia" 5 :m :hydro :bow :snezhnaya]
  ["Xinyan" 4 :f :pyro :claymore :liyue]
  ["Zhongli" 5 :m :geo :polearm :liyue]
  ["Albedo" 5 :m :geo :sword :mondstadt]
  ["Ganyu" 5 :f :cryo :bow :liyue]
  ["Xiao" 5 :m :anemo :polearm :liyue]
  ["Hu Tao" 5 :f :pyro :polearm :liyue]
  ["Rosaria" 4 :f :cryo :polearm :mondstadt]
  ["Yanfei" 4 :f :pyro :catalyst :liyue]
  ["Eula" 5 :f :cryo :claymore :mondstadt]
  ["Kaedehara Kazuha" 5 :m :anemo :sword :inazuma]
  ["Kamisato Ayaka" 5 :f :cryo :sword :inazuma]
  ["Sayu" 4 :f :anemo :claymore :inazuma]
  ["Yoimiya" 5 :f :pyro :bow :inazuma]
  ["Aloy" 5 :f :cryo :bow :none]
  ["Kujou Sara" 4 :f :electro :bow :inazuma]
  ["Raiden Shogun" 5 :f :electro :polearm :inazuma]
  ["Sangonomiya Kokomi" 5 :f :hydro :catalyst :inazuma]
  ["Thoma" 4 :m :pyro :polearm :inazuma]
  ["Arataki Itto" 5 :m :geo :claymore :inazuma]
  ["Gorou" 4 :m :geo :bow :inazuma]
  ["Shenhe" 5 :f :cryo :polearm :liyue]
  ["Yun Jin" 4 :f :geo :polearm :liyue]
  ["Yae Miko" 5 :f :electro :catalyst :inazuma]
  ["Kamisato Ayato" 5 :m :hydro :sword :inazuma]
  ["Yelan" 5 :f :hydro :bow :liyue]
  ["Kuki Shinobu" 4 :f :electro :sword :inazuma]
  ["Shikanoin Heizou" 4 :m :anemo :catalyst :inazuma]
  ["Collei" 4 :f :dendro :bow :sumeru]
  ["Tighnari" 5 :m :dendro :bow :sumeru]
  ["Dori" 4 :f :electro :claymore :sumeru]
  ["Candace" 4 :f :hydro :polearm :sumeru]
  ["Cyno" 5 :m :electro :polearm :sumeru]
  ["Nilou" 5 :f :hydro :sword :sumeru]
  ["Nahida" 5 :f :dendro :catalyst :sumeru]
  ["Layla" 4 :f :cryo :sword :sumeru]
  ["Faruzan" 4 :f :anemo :bow :sumeru]
  ["Wanderer" 5 :m :anemo :catalyst :sumeru]
  ["Alhaitham" 5 :m :dendro :sword :sumeru]
  ["Yaoyao" 4 :f :dendro :polearm :liyue]
  ["Dehya" 5 :f :pyro :claymore :sumeru]
  ["Mika" 4 :m :cryo :polearm :mondstadt]
  ["Baizhu" 5 :m :dendro :catalyst :liyue]
  ["Kaveh" 4 :m :dendro :claymore :sumeru]
  ["Kirara" 4 :f :dendro :sword :inazuma]
  ["Lynette" 4 :f :anemo :sword :fontaine]
  ["Lyney" 5 :m :pyro :bow :fontaine]
  ["Freminet" 4 :m :cryo :claymore :fontaine]
  ["Neuvillette" 5 :m :hydro :catalyst :fontaine]
  ["Wriothesley" 5 :m :cryo :catalyst :fontaine]
  ["Charlotte" 4 :f :cryo :catalyst :fontaine]
  ["Furina" 5 :f :hydro :sword :fontaine]
  ["Navia" 5 :f :geo :claymore :fontaine]
  ["Chevreuse" 4 :f :pyro :polearm :fontaine]
  ["Gaming" 4 :m :pyro :claymore :liyue]
  ["Xianyun" 5 :f :anemo :catalyst :liyue]
  ["Chiori" 5 :f :geo :sword :inazuma]
  ["Arlecchino" 5 :f :pyro :polearm :snezhnaya]
  ["Clorinde" 5 :f :electro :sword :fontaine]
  ["Sethos" 4 :m :electro :bow :sumeru]
  ["Sigewinne" 5 :f :hydro :bow :fontaine]
  ["Emilie" 5 :f :dendro :polearm :fontaine]
  ["Kachina" 4 :f :geo :polearm :natlan]
  ["Mualani" 5 :f :hydro :catalyst :natlan]
  ["Kinich" 5 :m :dendro :claymore :natlan]
  ["Xilonen" 5 :f :geo :sword :natlan]
  ["Chasca" 5 :f :anemo :bow :natlan]
  ["Ororon" 4 :m :electro :bow :natlan]
  ["Citlali" 5 :f :cryo :catalyst :natlan]
  ["Mavuika" 5 :f :pyro :claymore :natlan]
  ["Lan Yan" 4 :f :anemo :catalyst :liyue]
  ["Yumemizuki Mizuki" 5 :f :anemo :catalyst :inazuma]
  ["Iansan" 4 :f :electro :polearm :natlan]
  ["Varesa" 5 :f :electro :catalyst :natlan]
  ["Escoffier" 5 :f :cryo :polearm :fontaine]
  ["Ifa" 4 :m :anemo :catalyst :natlan]
  ["Dahlia" 4 :m :hydro :sword :mondstadt]
  ["Skirk" 5 :f :cryo :sword :none]
  ["Ineffa" 5 :f :electro :polearm :nod-krai]
  ["Aino" 4 :f :hydro :claymore :nod-krai]
  ["Lauma" 5 :f :dendro :catalyst :nod-krai]
  ["Flins" 5 :m :electro :polearm :nod-krai]
  ["Nefer" 5 :f :dendro :catalyst :nod-krai]
  ["Durin" 5 :m :pyro :sword :mondstadt]
  ["Jahoda" 4 :f :anemo :bow :nod-krai]
  ["Columbina" 5 :f :hydro :catalyst :nod-krai]
  ["Illuga" 4 :m :geo :polearm :nod-krai]
  ["Zibai" 5 :f :geo :sword :liyue]
  ["Varka" 5 :m :anemo :claymore :mondstadt]
  ["Linnea" 5 :f :geo :bow :nod-krai]
  ["Nicole" 5 :f :pyro :catalyst :none]
  ["Prune" 4 :f :anemo :catalyst :mondstadt]
  ["Lohen" 5 :m :cryo :polearm :mondstadt]
  ["Lumine" 5 :f :anemo :geo :electro :dendro :hydro :pyro :cryo :sword]
  ["Aether" 5 :m :anemo :geo :electro :dendro :hydro :pyro :cryo :sword]
  ["Manekin" 5 :m :anemo :geo :electro :dendro :hydro :pyro :cryo :sword]
  ["Manekina" 5 :f :anemo :geo :electro :dendro :hydro :pyro :cryo :sword]])